apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-jona-test
  namespace: jona-test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-jona-test-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: jona-test-gateway
                namespace: jona-test
                kind: Gateway