apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pocket-id-issuer
  namespace: cloudijs-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: pocket-id-issuer-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: pocket-id-gateway
                namespace: cloudijs-system
                kind: Gateway