---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: cloudijs-system
spec:
  encryptedData:
    encryption-key: AgCCBHw7Rh36uoh854/saDw0AUEAPH59fUzZn8HrJfg2jGlX8BijidZWh52ePfaIEwakLTqzHO0t4AIXcnprfuq0kkmiekm3Hs0q7IssfW/QjCBO0zy3/hXRZlbbC+syTKum02/Swl9Gp04qbUUVltoz2tzRDsYynvPmTOg7r0ms4gLc31C5wSMKMHwfgrfPpBhPN0cq6ePTS6uzVY2H8RhmdrUj57UWv6QDtnM5UPBuTRjJMI+TKIRpC/LgWtu41BqAaneJRrfqO7j1+dlt35CnlEB+N1g2fk42FouUVKejqSdbMP1YF7KIyI/1sJ/0Gtp1E+AQOT8OlA165OGcgYl/6BamvaJZ557dhS1+HKWy3QV98o6aYhTtER1e37QRx417unm6+d094qRvddZQzDPS/elH377Id7CX4AtEG+JMzKlRepXF2zjdGce8x8648tzehEIg2ORo4CcfE4Yn0QSrqWEPmDg0Gj5VSAm3SHm+s+wUwnejbkGd8rp0AiIhWazHYtbvumZSnn1GuHgbGpcs/0LQa80NMMRw5WSvZ+WvnAAmAtP8lt0FvjedqETnS8NgvROF0fz8tLdjOLxVzsmWpOfNPUG19uP8eCC1v4vmjwdViR23uhP3m5MnfSPtP6b5bFCtnnsz0hx4PVD+wI4TQeZHwee5tYD+LjYk1vooKQfexdcH8NHGNe6J9dw0zf5yu4I5pp1VFAfT2kQxklaL8KhCvQVojJDio2LSOsB6QF1L2QXObrbz8msYOg==
  template:
    metadata:
      name: pocket-id-secrets
      namespace: cloudijs-system
