---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: cloudijs-system
spec:
  encryptedData:
    encryption-key: AgAu6857UC/ZlG3onH71ZJZ0BdtiH+TNvGlsPsK9NbSla0aXhhaXFtLZwNXyocENpjtUe2VGZj6dA9mODK8TbNgwO3GRur2WdIbg64L3MHQzg3SzlShEFPtKPk0LYWWYNjVbfmi58ErTs60wvxVYrpSkNnfQAyV/rjncnQrG5rfZ7O8Ebg0IEgQIfTwHTrQgDSc42ETbwTKV1f1LZHaa/7aSxGv3djjG7xiIYORQHuHG7YFB45Zmp9h2dRDhLFsB8Soy71K6jgKj2IN3c8Hi7R49SKvKcAUPahATFBkNxEJPJ9UHwDkriwLhQ2c9XRbj5RJ1Rpw3auGmUdGOfloYBhS+PkEvzcdYyA2sYyK7lH6AdhhwulSq2CaYg+T+HRyTxcmdh6SHp8LzvwNA9bBerONztlR1cYGDzKfDDLPQHu3Aw2/VrKlTHJgn4j8DC/Gv28FfH0sAIHNzH4JMQKDUR7jSM3h97TR9JETKfnSwugBF1UwN7rfLlyQIUuy6VgZ+ObhJyT2cwwIXBL3IG0ZbH/aV5rpD6SbmP7g873ybVboQxzGVH0W4eqBxMev0coMiRussQV6Z6J2qWjEHdGnqRQpQExjKnrjHaZI/LrhO4d1451cM0OyhCqpUxJzeCuvXrWpTHdnL8LCfFGVg6KbM8tvGy9Rr1pwxYQ7lsI/8ehsxAyTVtM19e+PmG2ixMNBDHWbRwh6Gjxu+055NTQgD9PEtO1SR27nQ4gDm5I/4G3uuRdplB/HLX2eluDwMtg==
  template:
    metadata:
      name: pocket-id-secrets
      namespace: cloudijs-system
