---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: cloudijs-system
spec:
  encryptedData:
    encryption-key: AgBohrz5TkV2colS+UFzNnONrB4x4Czsi8CzUxnm3V53ggjQYH5DossqKKC057rJOPDZXQQ2y7YMGkEJ9EZv0nowiGycTCzSa4VtjTwzwPbMyGhwkPYhJ5S6lTanVjGpDYcRb6u3JmRUYaS8SraFNGyThK1L5HPgGio1xXfaO6jaUYh39JRZZGjcN5t46ySDp2G7m6HK6J8GpgPCHfxlylbAznPDeHAk1SoS0mPuISyOggv8lAMEq4s5Xu/dIRVPH9CLHa08Jn3NsNdzKCM4sD78oYVZMQct0/Nn9aT85dewIWg5lYLU2G2EuuWRcwwHKfZHwzJRLQ/kdXQ5X824GLBEQckrFSB2E2415zB9ARpmwP1XwOuX60GEk4E1ak3Mtd4Yc4rRINPwh4YQZfD5Etk+RNndimBMIGYMb/K8NSoJmnnC0URJFSFPKjwM0jSLFSc6gU3e45m2uw81wx5hmSDV6IyeLGDTcgKoWst3ZFXTeMo166aGy6SQeT9m8sn4/gDxN8JSWh2ljUayV0c1Nudx+8ixbJ5rMUbmHMrIk/PN7bY51uKWDL0BmqG8FwIjOoyEn5ERA2GOlnczCbSwuUXC0/QuBvdFexXNSOny1v1b/tUCY6yZHE2klq6t+2FHrQfme4bOgqQmCpOHndoQPFuLdylTu4PnPy7yfcWIyFLKkXkBsuOnGSjgmg6X5bi1txk/M+SCARhIRfF3BWYvCDwEd1yDDwlTwAdVNnc5ncG42H8ky238aYvisqGh59w=
  template:
    metadata:
      name: pocket-id-secrets
      namespace: cloudijs-system
