apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sample-nginx-issuer
  namespace: apps
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: sample-nginx-issuer-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: sample-nginx-gateway
                namespace: apps
                kind: Gateway