apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: cloudijs-monitoring
spec:
  interval: 1h
  url: https://grafana-community.github.io/helm-charts
