apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: cloudijs-test-2
  namespace: apps
spec:
  parentRef:
    name: shared-gateway-http
    namespace: cloudijs-system
    kind: Gateway
  listeners:
    - name: cloudijs-test-2
      hostname: test-2.cloudijs.nl
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: test-2-cloudijs-nl-tls
            kind: Secret
            group: ""
