---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flux-web-client
  namespace: cloudijs-system
spec:
  encryptedData:
    client-id: AgBwLKiWT7QMqER00q55//wEGEiAcGQ33fkMpZammh7WmDFiJxdKawzL2lQRt1Guv993Z1FItj6pDrNXuOPIvS7dlSpA2+fhbG7YlJTB8Ig0JXUukhnuET4CKXraw0DODdBFalfw4eDp8lQ3xgGY11Ho4sZgTrrJAo7nkMRWRevfDiyYZezDvOLTNXeP9u/0We4m3Q/v/AVrPju6vZbRAzvla95qio1g507eGjwVrNEgs54qrIKbHFZHbobU2S42jMbtERP/kchanWFm1X4/3jDDGtf5OMqRjE5kLmu3G5jL3a//5fT+bUUr9tlruFR9aIRVpCewb85gs34Kaetxnu9gW12x4fqoUPK7F0HtZNrcmPChmgdQOKGgd+88IZN1c4o1ogvIDl6u3yaQLE7YCgXlECyQRRAyRJ5pXelf2vkJ95GpdeAYeSbyasljLS3d8Qd99HI3ozFF9wwat8PHehA+r5DhNJwf1jTYuvY9WIEqlZ3ATk0mTTrWXFE9ouabpbsvjyH+KAxCHaGoW4RsJsyYT3EWXj9bUV6pN7S+tfVEhF5vSUuAe+I1Beto7SsjptM/crfPyHY3gpudeqYAnmkPhXUatLNsXUR65FPO0/54iePrmZqbX0IrW00k1bxulFERiwrK08uWpVL3OTTEQlHOQJPbdUgK1fTPFsM7OwMWRDRr57lT4HaTPT5DwTPY9twXrTUca1wz9l2Wp6s3Bp8aXnpDRTIOPWr0yC2lZCifGlDv7LI=
    client-secret: AgCzsX65XQzKlS5xO1Yt0X98iSUtcW83TRFIKgmmqSW+K2XBZpzanZKPn23OFcfRtwHrpEN81Lh0QqJQSM8ynMujdxRfG+AThVXHeJYHMMUrNYGzklLakHQ2lDYhW6a5DdhOxnVTcSURpxZvotmoSpneYZFPvoGffmkHbfD75u0HXqGfoJH6Vjvq7gcfd/VSPGkOekypMOQVb/rsbvv/IQkALiHCi5/NR1/tRm/WtqmVfh56oS41xslRQhmlxfIbtD3ryoYw863+/nx6sO2pFBHHhxdrrlPmPPJLvge/R7njcHkCrMmHjsnuoiLoshQt+YAoJNXcDogGStjxxpmbeAhjEqLi39W2RT858Chps41+M/kF3NIbqxgRkbs58HVMzI7py9H+P8IQ1K5ZOfuK0z0nkUIlKRRhugMTxDYF92EJQhbCZ83s4WbEZu7wli8o5cqjyFXWfq8C90zDftEi5KI4dc+Wl6CsuFYkmKIeNd7QvoFD5hNK2xYDpRuVihtZq64uCPVZIZH8aam0USu3V72gVbPchVPxXOX6FRAPtcyWQDVlBxnivw8/M8wFjOlYw/rrnbDkV9oqYz4ks5Y+l1KNAIXSSUs3eZTyHx9n0EM+qyyPM2vuWzAOa+TdgjXpQtB1ik5tXaYT2ddnK4uMPHWszieitvNzeWCApvVE7GhR3xviFL/OkptZc48d/zUmMPA9is4dOgmmTfvFAhKqA/7lcs6RlpAYhxXGfjo94HwqpA==
  template:
    metadata:
      name: flux-web-client
      namespace: cloudijs-system
