name: Apply Terraform plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply Terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform apply
        uses: dflook/terraform-apply@v2
        with:
          path: terraform
          backend_config: |
            bucket=${{ secrets.TF_STATE_BUCKET_NAME }}
            access_key=${{ secrets.TF_STATE_ACCESS_KEY }}
            secret_key=${{ secrets.TF_STATE_SECRET_KEY }}