name: Lint Terraform plan

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform validate
        uses: dflook/terraform-validate@v2
        with:
          path: terraform

  fmt-check:
    runs-on: ubuntu-latest
    name: Terraform formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform fmt
        uses: dflook/terraform-fmt-check@v2
        with:
          path: terraform