name: Create Terraform plan

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a Terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_STATE_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_STATE_SECRET_KEY }}
      AWS_CA_BUNDLE: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform plan
        uses: dflook/terraform-plan@v2
        with:
          path: terraform